test:
      my:
          string: " I Kick you "

---
spring:
        profiles: Dev

test:
      my:
          string: " I Love you "

---
spring:
        profiles: Test

test:
      my:
          string: " I Hate you "




